OUTPUT_DIR: 'output'
WORKERS: 4
PRINT_FREQ: 10

DATASET:
  NUM_CLASSES: 8
LOSS:
  USE_OHEM: true
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
TRAIN:
  IMAGE_SIZE:
  - 520
  - 520
  BASE_SIZE: 520
  BATCH_SIZE_PER_GPU: 4
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 120
  RESUME: true
  OPTIMIZER: sgd
  LR: 0.02
  WD: 0.0001
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: true
  MULTI_SCALE: true
  DOWNSAMPLERATE: 1
  IGNORE_LABEL: 255
  SCALE_FACTOR: 11
TEST:
  IMAGE_SIZE:
  - 520
  - 520
  BASE_SIZE: 520
  BATCH_SIZE_PER_GPU: 1
  NUM_SAMPLES: 200
  FLIP_TEST: false
  MULTI_SCALE: false
